apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: spring-cloud-gateway
data:
  prueba: sss
  application.yaml: |-
    server:
      port: 8080
    spring:
      cloud:
        gateway:
          routes:
            - id: codechallenge
              uri: http://codechallenge2:8080
              predicates:
              - Path=/codechallenge/**
              filters:
                - StripPrefix=1
            - id: codechallenge2 
              uri: http://codechallenge2:8080
              predicates:
                - Path=/codechallenge2/**
              filters:
                - StripPrefix=1
            - id: default
              uri: https://seguro.santalucia.es/
              predicates:
                - path=/**
              
    
    management:
      server:
        port: 8081
      endpoints:
        web:
          base-path: /management
          exposure:
            include:
              - "*"
               
    logging:
      level:
        org.springframework.cloud.gateway.handler.predicate: trace
  